---
- hosts: all
  connection: local

  tasks:
    - include: tasks/user.yml
      tags: user

    - include: tasks/packages.yml
      tags: packages

    - include: tasks/dotfiles.yml
      tags: dotfiles

    - include: tasks/os_customisation.yml
      tags: os_customisation

  roles:
    - role: rvm_io.ruby
      tags: ruby
      rvm1_rubies: ['ruby-2.5.1']
      rvm1_install_flags: '--auto-dotfiles  --user-install'
      rvm1_user: "{{ username }}"

## TODO
# pyenv
# jetbrains toolbox and rubymine
# nvidia drivers
# template git username and email
# terminal config - fonts, etc

