---
- hosts: all
  connection: local

  tasks:
    # - include: tasks/user.yml
    #   tags: user

    - include: tasks/packages.yml
      tags: packages

    - include: tasks/node.yml
      tags: node

    - include: tasks/dotfiles.yml
      tags: dotfiles

    - include: tasks/fonts.yml
      tags: fonts

    - include: tasks/plank.yml
      tags: plank

    - include: tasks/random_config.yml
      tags: random_config

  roles:
    - role: rvm_io.ruby
      tags: ruby
      rvm1_rubies: ['ruby-2.5.1']
      rvm1_install_flags: '--auto-dotfiles  --user-install'
      rvm1_user: "{{ username }}"

## TODO
# pyenv
# nvidia drivers
# terminal config - fonts, etc

