apt_packages:
  - build-essential
  - byobu
  - cmatrix
  - cowsay
  - curl
  - git-core
  - git-extras
  - htop
  - imagemagick
  - jq
  - nmap
  - sl
  - telnet
  - tree
  - mysql-server
  - libmysqlclient-dev
  - frozen-bubble
  - frozen-bubble-data
  - k4dirstat
  - keepassx
  - meld
  - openssh-server
  - shutter
  - transgui
  - unity-tweak-tool
  - vlc
  - zenmap
  - virtualbox-5.2
#  - dkms
#  - libcurl3
#  - spotify-client
#  - google-chrome-stable
#  - oracle-java8-installer
  - firefox
  - neofetch
  - steam-installer
  - darktable
  - hexchat
  - caja-dropbox
  - tilix
  - docker.io # until ansible ppa available for bionic
  - rsync
  - unrar
  - p7zip-full
  - p7zip-rar
  - vim
  - mono-complete
  - gtk-sharp2

pyenv_packages:
  - make
  - libbz2-dev
  - libreadline-dev
  - libsqlite3-dev
  - llvm
  - libncursesw5-dev
  - xz-utils
  - tk-dev

apt_signing_keys:
  - https://www.virtualbox.org/download/oracle_vbox_2016.asc
  - https://www.virtualbox.org/download/oracle_vbox.asc
  - https://dl-ssl.google.com/linux/linux_signing_key.pub
  - https://download.docker.com/linux/ubuntu/gpg

ubuntu_keyserver_keys:
  - 0DF731E45CE24F27EEEB1450EFDC8610341D9410 # spotify

apt_repositories:
  - "deb http://download.virtualbox.org/virtualbox/debian {{ ubuntu_distribution }} contrib"
  - "deb http://repository.spotify.com stable non-free"
  #- "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main"
  # - "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ubuntu_distribution }} stable"

ppa_repositories:
  #- "ppa:webupd8team/java"
  - "ppa:pmjdebruijn/darktable-release"

debs:
  - https://www.dropbox.com/download?dl=packages/ubuntu/dropbox_2015.10.28_amd64.deb
  - http://ftp.debian.org/debian/pool/contrib/m/msttcorefonts/ttf-mscorefonts-installer_3.6_all.deb
#  - https://steamcdn-a.akamaihd.net/client/installer/steam.deb
  - https://go.microsoft.com/fwlink/?LinkID=760868 # vscode
  - https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb



# random stuff in zips/tars/gz etc 

non_standard_packages:
  - name: pablodraw
    url: http://download.picoe.ca/pablodraw/3.2/PabloDraw-3.2.1.zip
    version: 3.2.1

# stuff in rar packages (seriously?!)

rar_packages:
  - name: netrunner
    url: http://www.mysticbbs.com/downloads/nr20b186.rar
    version: 2.0b186